CREATE TABLE lists(
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE todos(
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  list_id int NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
  completed boolean NOT NULL DEFAULT false
);
